import PageIntro from "./PageIntro";
import Topic from "./reusable-components/Topic.jsx";

function Main () {

    return (
        <main>
            <PageIntro />
            <div className="topic-container">
                <Topic title="Maximum utilization leads to the next step">
                    <p className="topic-content">This topic will focus on the importance of learning things through steps. There is a huge abundance of tools that can make your life easier as a developer. With new libraries and frameworks coming out frequently, it is inevitable for the older ones to become redundant but that shouldn't discourage you from learning them as long as they are still applicable and can get the job done.</p>
                    <p className="topic-content">Understanding why certain things work the way they do is obviously a given requirement when learning new things. And even though, the learning process of Web Development is a lot more forgiving when it comes to taking what I would call a shortcut for lack of a better way to describe it, I would advise you to keep doing things the way you normally do until you reach the point where it's near impossible to progress any further with what you have in your arsenal. The downside of this is that it is a much slower progress but, of course, it also comes with a benefit. When you eventually reach a wall, the tools that you need in order to get across should be a lot clearer to you. It helps to keep your thoughts organize and straightforward when the problem presents itself. As I mentioned earlier, there are so many things that we can use to our advantage that we sometimes feel the need to make use of them as a response to the fear of getting left behind. But, believe me when I say that, a lot of the time it's better to write your own CSS, and sometimes Frameworks can be a bit overkill. </p>
                    <p className="topic-content">With all that being said, I'm not trying to discourage anyone from branching out earlier on especially if you thrive in that kind of learning process but, you also shouldn't be afraid of sticking to your guns. Keep reusing the same techniques, and keep writing codes the way you do until eventually the limits of your tools will point towards the next appropriate steps.</p>
                </Topic>
                <Topic title="Overcoming the first hurdle">
                    <p className="topic-content">While a year may seem like plenty enough of time to learn Web Development at a sufficient level, for a lazy person like me, it's a tough challenge, to say the least. Whenever I compare what others have achieved in a year versus my progression, it feels like I just learned how to ride a bike while they are already piloting a plane. Of course, most of it if not all is my own fault for not putting in the same amount of work as others have, but you really can't underestimate how much your mental state can affect your progress. Having suffered from both burnout and lack of motivation simultaneously, I'm surprised to still be in this field, thriving and continuing to learn. </p>
                    <p className="topic-content">I didn't particularly have a concrete solution to deal with said issues. However, I do know that being persistent got me where I am today. It took a lot of detours and sacrifices, sometimes I would take a break for a few days maybe weeks, I would give up on projects that I deemed too advanced for my skills, and I would copy someone else's solution to a problem that I am too lazy to solve. I did all of that while telling myself “This isn't for me”, but somehow, I always find myself reading through documents and relearning everything from the basics. It was a hard situation to be in, but I managed to persevere through it by looking at my problems from a different angle as well as changing my approach.</p>
                    <p className="topic-content">Burnout or lack of motivation is a very common thing to experience generally, especially during the early stage of a learning process when there is hardly any progress. You could easily spiral into a series of negative thoughts that slowly eats away your passion. And to be honest, I think being a victim of burnout has helped me realize that this is what I want to do. It's not the first time I experienced burnout, but this is definitely the first time where I couldn't completely walk away from what I was trying to achieve. I just kept coming back with a different perspective, ideas, and approach until eventually, everything started to move forward again. </p>
                </Topic>
                <Topic title="lorem ipsum">
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sapiente asperiores at optio ut beatae natus, iure esse facilis commodi. Aspernatur officiis omnis ex quis, earum ratione perferendis sapiente ut nisi assumenda nemo facilis maxime vitae! Eius sed eveniet doloremque nulla ab nesciunt animi ipsam quasi natus! Officiis, laudantium eligendi?</p>
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo sunt quos quo, fuga eaque possimus odit cum veritatis atque expedita architecto aspernatur modi aut mollitia, ea molestias aperiam libero facere maxime consequuntur quaerat? Cumque quisquam cupiditate eos eligendi saepe laborum debitis eaque! Id esse obcaecati veritatis culpa tempore quidem eum alias? Facere sint, enim quidem at dolorum consequuntur dolorem sed ipsam totam, facilis deleniti perferendis voluptatibus eligendi accusantium? Ea excepturi, distinctio cum eos magnam vero harum inventore quidem aperiam earum perferendis, expedita dolorum placeat debitis molestiae eaque error quam deleniti facere iusto delectus! Excepturi quasi officia quas? Assumenda, quasi recusandae.</p>
                </Topic>
                <Topic title="lorem ipsum">
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sapiente asperiores at optio ut beatae natus, iure esse facilis commodi. Aspernatur officiis omnis ex quis, earum ratione perferendis sapiente ut nisi assumenda nemo facilis maxime vitae! Eius sed eveniet doloremque nulla ab nesciunt animi ipsam quasi natus! Officiis, laudantium eligendi?</p>
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo sunt quos quo, fuga eaque possimus odit cum veritatis atque expedita architecto aspernatur modi aut mollitia, ea molestias aperiam libero facere maxime consequuntur quaerat? Cumque quisquam cupiditate eos eligendi saepe laborum debitis eaque! Id esse obcaecati veritatis culpa tempore quidem eum alias? Facere sint, enim quidem at dolorum consequuntur dolorem sed ipsam totam, facilis deleniti perferendis voluptatibus eligendi accusantium? Ea excepturi, distinctio cum eos magnam vero harum inventore quidem aperiam earum perferendis, expedita dolorum placeat debitis molestiae eaque error quam deleniti facere iusto delectus! Excepturi quasi officia quas? Assumenda, quasi recusandae.</p>
                </Topic>
                <Topic title="lorem ipsum">
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sapiente asperiores at optio ut beatae natus, iure esse facilis commodi. Aspernatur officiis omnis ex quis, earum ratione perferendis sapiente ut nisi assumenda nemo facilis maxime vitae! Eius sed eveniet doloremque nulla ab nesciunt animi ipsam quasi natus! Officiis, laudantium eligendi?</p>
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo sunt quos quo, fuga eaque possimus odit cum veritatis atque expedita architecto aspernatur modi aut mollitia, ea molestias aperiam libero facere maxime consequuntur quaerat? Cumque quisquam cupiditate eos eligendi saepe laborum debitis eaque! Id esse obcaecati veritatis culpa tempore quidem eum alias? Facere sint, enim quidem at dolorum consequuntur dolorem sed ipsam totam, facilis deleniti perferendis voluptatibus eligendi accusantium? Ea excepturi, distinctio cum eos magnam vero harum inventore quidem aperiam earum perferendis, expedita dolorum placeat debitis molestiae eaque error quam deleniti facere iusto delectus! Excepturi quasi officia quas? Assumenda, quasi recusandae.</p>
                </Topic>
                <Topic title="lorem ipsum">
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sapiente asperiores at optio ut beatae natus, iure esse facilis commodi. Aspernatur officiis omnis ex quis, earum ratione perferendis sapiente ut nisi assumenda nemo facilis maxime vitae! Eius sed eveniet doloremque nulla ab nesciunt animi ipsam quasi natus! Officiis, laudantium eligendi?</p>
                    <p className="topic-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo sunt quos quo, fuga eaque possimus odit cum veritatis atque expedita architecto aspernatur modi aut mollitia, ea molestias aperiam libero facere maxime consequuntur quaerat? Cumque quisquam cupiditate eos eligendi saepe laborum debitis eaque! Id esse obcaecati veritatis culpa tempore quidem eum alias? Facere sint, enim quidem at dolorum consequuntur dolorem sed ipsam totam, facilis deleniti perferendis voluptatibus eligendi accusantium? Ea excepturi, distinctio cum eos magnam vero harum inventore quidem aperiam earum perferendis, expedita dolorum placeat debitis molestiae eaque error quam deleniti facere iusto delectus! Excepturi quasi officia quas? Assumenda, quasi recusandae.</p>
                </Topic>
            </div>
        </main>
    )
}

export default Main;